"""add_external_refs

Revision ID: 0a786e0f2531
Revises: 9d6d5a58a076
Create Date: 2025-05-04 21:39:13.835726

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0a786e0f2531"
down_revision: Union[str, None] = "9d6d5a58a076"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organization",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("external_ref_id", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("website", sa.String(), nullable=True),
        sa.Column("logo_url", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_organization_name"), "organization", ["name"], unique=False
    )
    op.create_index(
        op.f("ix_organization_external_ref_id"),
        "organization",
        ["external_ref_id"],
        unique=True,
    )

    op.create_table(
        "office",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("external_ref_id", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("address", sa.String(), nullable=False),
        sa.Column("lat", sa.Float(), nullable=False),
        sa.Column("lng", sa.Float(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_office_name"), "office", ["name"], unique=False)
    op.create_index(
        op.f("ix_office_external_ref_id"), "office", ["external_ref_id"], unique=True
    )

    op.create_table(
        "rate",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("office_id", sa.Uuid(), nullable=False),
        sa.Column("currency", sa.String(), nullable=False),
        sa.Column("buy_rate", sa.Float(), nullable=False),
        sa.Column("sell_rate", sa.Float(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["office_id"],
            ["office.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_rate_currency"), "rate", ["currency"], unique=False)
    op.create_index(op.f("ix_rate_timestamp"), "rate", ["timestamp"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_rate_timestamp"), table_name="rate")
    op.drop_index(op.f("ix_rate_currency"), table_name="rate")
    op.drop_table("rate")
    op.drop_index(op.f("ix_office_external_ref_id"), table_name="office")
    op.drop_index(op.f("ix_office_name"), table_name="office")
    op.drop_table("office")
    op.drop_index(op.f("ix_organization_external_ref_id"), table_name="organization")
    op.drop_index(op.f("ix_organization_name"), table_name="organization")
    op.drop_table("organization")
    # ### end Alembic commands ###
